on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: MongoDB
        uses: supercharge/mongodb-github-action@1.4.0
        with:
          mongodb-version: 4.4
          mongodb-replica-set: rs0
      - name: Test
        run: go test ./...
